services:
  student-center-api:
    container_name: student-center-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"   
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys